Update built-in-schedules.mdx
Minor corrections to code samples:

  * In https://effect.website/docs/guide/scheduling/built-in-schedules#forever
    Remove () in use of Schedule.forever to prevent error:
    
    TSError: ⨯ Unable to compile TypeScript:
    error TS2349: This expression is not callable.
      Type 'Schedule<never, unknown, number>' has no call signatures.
    
    12 const schedule = Schedule.forever()
                                 ~~~~~~~
    

  * In https://effect.website/docs/guide/scheduling/built-in-schedules#once
    Remove () in use of Schedule.once to prevent error:
    
    error TS2349: This expression is not callable.
      Type 'Schedule<never, unknown, void>' has no call signatures.
    
    12 const schedule = Schedule.once()
                                 ~~~~


  * In https://effect.website/docs/guide/scheduling/built-in-schedules#fibonacci
    Replace

      Effect.runPromise(Schedule.run(schedule, 0, [1, 2, 3, 4, 5, 6])).then(
        console.log
      )

    with

      Effect.runPromise(Effect.repeat(logDelay, schedule))

    so that output matches expected output shown in comments instead of
      
      {
        _tag: 'Chunk',
        values: [
          { _tag: 'Duration', value: [Object] },
          { _tag: 'Duration', value: [Object] },
          { _tag: 'Duration', value: [Object] },
          { _tag: 'Duration', value: [Object] },
          { _tag: 'Duration', value: [Object] },
          { _tag: 'Duration', value: [Object] }
        ]
      }